CREATE TABLE tickets (
    -- Ticket ids continue after the Day 1 CSV ids (1001..).
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    customer_id  BIGINT                   NOT NULL,
    subject      VARCHAR(200)             NOT NULL,
    status       VARCHAR(20)              NOT NULL,
    priority     VARCHAR(20)              NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    version      BIGINT                   NOT NULL DEFAULT 0,

    -- No ON DELETE CASCADE: deleting a customer who still has tickets must fail, not silently remove history.
    CONSTRAINT fk_tickets_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_tickets_status CHECK (status IN ('OPEN', 'PENDING', 'CLOSED')),
    CONSTRAINT ck_tickets_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH'))
);

-- Audit trail. A row is written in the same transaction as every status change.
CREATE TABLE ticket_status_changes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id    BIGINT                   NOT NULL,
    from_status  VARCHAR(20),
    to_status    VARCHAR(20)              NOT NULL,
    changed_at   TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_status_changes_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE
);
