-- Flyway owns the schema. Hibernate only validates it (spring.jpa.hibernate.ddl-auto=validate).
-- Never edit a migration after it has run anywhere: add a new V<n>__ file instead.

CREATE TABLE customers (
    -- Ids start at 100 so they line up with the Day 1 ticket files (C-100, C-101, ...).
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    email       VARCHAR(254)             NOT NULL,
    tier        VARCHAR(20)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Optimistic locking: Hibernate increments this on every update and rejects stale writes.
    version     BIGINT                   NOT NULL DEFAULT 0,

    -- The unique constraint is backed by an index, so lookups by email are fast without CREATE INDEX.
    -- The application lower-cases emails before saving, which keeps this case-insensitive.
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_tier CHECK (tier IN ('STANDARD', 'PREMIUM'))
);
